backend:
  name: github
  repo: GaelleOd/Site-G
  branch: main
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "produits"
    label: "Produits"
    folder: "content/produits"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Prix", name: "price", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
